/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sandbox;

/**
 *
 * @author Sakis
 */
public class Sandbox extends javax.swing.JFrame {

    /**
     * Creates new form Sandbox
     */
    public Sandbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        play = new javax.swing.JLabel();
        tutorialPanel = new javax.swing.JPanel();
        tutorial_igotit = new javax.swing.JLabel();
        tutorial_book = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Score 4!");
        setBackground(new java.awt.Color(0, 102, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(960, 720));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/imgs/game_logo.png"))); // NOI18N
        menuPanel.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/imgs/menu_play.png"))); // NOI18N
        menuPanel.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        getContentPane().add(menuPanel);

        tutorialPanel.setBackground(new java.awt.Color(162, 192, 242));
        tutorialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tutorialPanel.setVisible(false);

        tutorial_igotit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/imgs/tutorial_igotit.png"))); // NOI18N
        tutorialPanel.add(tutorial_igotit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        tutorial_book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/imgs/tutorial_book.png"))); // NOI18N
        tutorialPanel.add(tutorial_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(tutorialPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sandbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sandbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sandbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sandbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sandbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel menu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel play;
    private javax.swing.JPanel tutorialPanel;
    private javax.swing.JLabel tutorial_book;
    private javax.swing.JLabel tutorial_igotit;
    // End of variables declaration//GEN-END:variables
}
