# -*- coding: utf-8 -*-
"""Ergasia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3sxgb6zu5p-CXBBWMKg-UgheI8XBMNa
"""

from PIL import Image
from google.colab import drive


import matplotlib
import numpy as np
import os
import time

import tensorflow

drive.mount("/content/drive")
os.chdir('/content/drive/MyDrive/Xray dataset/')
print(os.getcwd())
print("\n\n")
print(os.listdir())

os.chdir('./test_images/')
print(os.listdir())
for image in os.listdir():
  continue

def resize(image_pil, width, height):
    '''
    Resize PIL image keeping ratio and using white background.
    '''
    ratio_w = width / image_pil.width
    ratio_h = height / image_pil.height
    if ratio_w < ratio_h:
        # It must be fixed by width
        resize_width = width
        resize_height = round(ratio_w * image_pil.height)
    else:
        # Fixed by height
        resize_width = round(ratio_h * image_pil.width)
        resize_height = height
    image_resize = image_pil.resize((resize_width, resize_height), Image.ANTIALIAS)
    background = Image.new('RGBA', (width, height), (255, 255, 255, 255))
    offset = (round((width - resize_width) / 2), round((height - resize_height) / 2))
    background.paste(image_resize, offset)
    return background.convert('RGB')

image_list = []

for filename in ('../Xray dataset/train_images/*'): #assuming gif
    im=Image.open(filename)
    image_list.append(im)

print(image_list)

from tensorflow import keras