/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quad.Panels;

import java.awt.Dimension;

/**
 *
 * @author user
 */
public class gameScreen extends javax.swing.JPanel {

    /* 
        * ***When filling the Board note that :***
        * 0 = Empty Slot
        * 1 = Player_1
        * 2 = Player_2
        */
    
    public gameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(980, 720));
        setLayout(new java.awt.GridLayout(7, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
