import java.sql.Connection;


public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaIpallilonButton = new javax.swing.JButton();
        ListaPelatonButton = new javax.swing.JButton();
        KratiseisButton = new javax.swing.JButton();
        ApothemataButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaIpallilonButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ListaIpallilonButton.setText("Λίστα Υπαλλήλων");
        ListaIpallilonButton.setToolTipText("Λίστα Υπαλλήλων");
        ListaIpallilonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaIpallilonButtonActionPerformed(evt);
            }
        });

        ListaPelatonButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ListaPelatonButton.setText("Λίστα Πελατών");
        ListaPelatonButton.setToolTipText("Λίστα Πελατών");
        ListaPelatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPelatonButtonActionPerformed(evt);
            }
        });

        KratiseisButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KratiseisButton.setText("Κρατήσεις");
        KratiseisButton.setToolTipText("Κρατήσεις");
        KratiseisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KratiseisButtonActionPerformed(evt);
            }
        });

        ApothemataButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ApothemataButton.setText("Αποθέματα");
        ApothemataButton.setToolTipText("Αποθέματα");
        ApothemataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApothemataButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ΒΑΣΗ ΔΕΔΟΜΕΝΩΝ ΒΙΒΛΙΟΘΗΚΗΣ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ApothemataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ListaPelatonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListaIpallilonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KratiseisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ListaIpallilonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(ListaPelatonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(KratiseisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(ApothemataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaIpallilonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaIpallilonButtonActionPerformed
        ListaIpallilon ipalliloi = new ListaIpallilon();
        ipalliloi.setVisible(true);
    }//GEN-LAST:event_ListaIpallilonButtonActionPerformed

    private void ListaPelatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPelatonButtonActionPerformed
        ListaPelaton pelates = new ListaPelaton();
        pelates.setVisible(true);
    }//GEN-LAST:event_ListaPelatonButtonActionPerformed

    private void KratiseisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KratiseisButtonActionPerformed
        Kratiseis kratiseis = new Kratiseis();
        kratiseis.setVisible(true);
    }//GEN-LAST:event_KratiseisButtonActionPerformed

    private void ApothemataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApothemataButtonActionPerformed
        ListaBiblion apothemata = new ListaBiblion();
        apothemata.setVisible(true);
    }//GEN-LAST:event_ApothemataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApothemataButton;
    private javax.swing.JButton KratiseisButton;
    private javax.swing.JButton ListaIpallilonButton;
    private javax.swing.JButton ListaPelatonButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
